# Generated by Django 4.0.6 on 2023-04-11 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamDegrees',
            new_name='ExamDegree',
        ),
    ]
