# Generated by Django 4.0.6 on 2023-04-12 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_lessonquestion_alter_subjectquestionreply_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectQuestionReply',
            new_name='LessonQuestionReply',
        ),
    ]
