# Generated by Django 4.0.6 on 2023-04-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_rename_subjectquestionreply_lessonquestionreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreply',
            name='replier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
