# Generated by Django 4.1.5 on 2023-04-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_complaintreply_replier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stage',
            new_name='Phase',
        ),
        migrations.RenameField(
            model_name='pathinfo',
            old_name='stage',
            new_name='phase',
        ),
        migrations.RemoveField(
            model_name='pathinfo',
            name='students',
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/academies_images'),
        ),
    ]
