# Generated by Django 4.1.5 on 2023-04-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_stage_phase_rename_stage_pathinfo_phase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademyFeautre',
            new_name='AcademyFeature',
        ),
    ]
