# Generated by Django 4.1.5 on 2023-04-29 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_rename_academyfeautre_academyfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathinfo',
            name='students',
            field=models.ManyToManyField(related_name='in_academies', through='main.Student', to=settings.AUTH_USER_MODEL),
        ),
    ]
