# Generated by Django 4.0.6 on 2023-05-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pathinfo_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='academydetail',
            name='landing_photo',
            field=models.ImageField(default='null', upload_to='images/academies_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academy',
            name='logo',
            field=models.ImageField(default='null', upload_to='images/academies_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academy',
            name='academy_type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies', to='main.academytype'),
        ),
    ]
