# Generated by Django 4.1.5 on 2023-04-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pathinfo_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='academydetail',
            name='landing_photo',
            field=models.ImageField(default='images/academies_images/zov6rwZ1L3AMtnxAzsNXWvR4EqfgPQuVjvIXuTLl.jpg/', upload_to='images/academies_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academy',
            name='logo',
            field=models.ImageField(default='images/academies_images/zov6rwZ1L3AMtnxAzsNXWvR4EqfgPQuVjvIXuTLl.jpg/', upload_to='images/academies_images'),
            preserve_default=False,
        ),
    ]
