# Generated by Django 4.0.6 on 2023-05-30 06:40

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_academytype_academydetail_landing_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Academy',
            name='academy_type',
        ),
    ]
