# Generated by Django 4.0.6 on 2023-05-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_academy_academy_type_alter_academy_academy_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='academy_type',
        ),
    ]
