# Generated by Django 4.0.6 on 2023-06-22 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_academy_type2_academy_academy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
