# Generated by Django 4.0.6 on 2023-07-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_academy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
